# Generated by Django 5.1.3 on 2024-12-05 00:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendarapp', '0003_alter_event_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=50)),
                ('Description', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='event',
            name='request',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='calendarapp.request'),
        ),
    ]
