# Generated by Django 5.1.4 on 2024-12-08 15:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendarapp', '0007_alter_event_request'),
    ]

    operations = [
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='event',
            name='state',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='calendarapp.state'),
        ),
    ]
