# Generated by Django 5.1.4 on 2024-12-08 16:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendarapp', '0010_alter_state_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='state',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='states', to='calendarapp.state'),
        ),
    ]
